### PR TITLE
Fix indexing JArray / faster IList indexing

### LINKED ISSUE #797: Access JObject in index failed
When I try to access vaue in `items[0]`, it threw error below:
image

To reproduce:
make a json string like
```
{
  "items": [{"p1": 1}],
  "row": 1
}
```
Then use `JObject.Parse(Response.Content)` to get a `JObject`.

Below is my ugly fix, convert string `"0"` to int `0`:
image

### PR DESCRIPTION
**Pull request by lahma**
* protect `ClrTypeConverter` from changing during engine lifetime, should set via options
* make specialized property handlers internal, they're already sealed so let's not expose too much
* improve `TryFindIndexer` to account directly for `IList` and short-circuit there for indexer when parameter is convertible to number
* improve performance by detecting integer array indexer access

fixes #797

### CODE REVIEW

File: Jint/Runtime/Descriptors/Specialized/IndexDescriptor.cs [hunk 1]
```diff
@@ -1,47 +1,64 @@
...
             var paramTypeArray = new Type[1];
+            Func<object, IndexDescriptor> ComposeIndexerFactory(PropertyInfo candidate, Type paramType)
+            {
+                if (engine.ClrTypeConverter.TryConvert(propertyName, paramType, CultureInfo.InvariantCulture, out var key))
+                {
+                    // the key can be converted for this indexer
+                    var indexerProperty = candidate;
+                    // get contains key method to avoid index exception being thrown in dictionaries
+                    paramTypeArray[0] = paramType;
+                    var containsKeyMethod = targetType.GetMethod("ContainsKey", paramTypeArray);
```
Comment (sebastienros) [inline Jint/Runtime/Descriptors/Specialized/IndexDescriptor.cs:45]: nameof?

No biggy since it was like it already.
Another matter for later is to cache all these reflection paths ...

**Review by sebastienros — APPROVED** [review]

File: Jint/Runtime/Descriptors/Specialized/IndexDescriptor.cs (hunk 1 above)
Comment (lahma) [reply Jint/Runtime/Descriptors/Specialized/IndexDescriptor.cs:45]: Good improvement, changed to `nameof` and also included `IDictionary.Contains`
