### PR TITLE
Fix instanceof logic to comply with specification

### LINKED ISSUE #874: "instanceof" operator doesn't work according to the latest spec
https://tc39.es/ecma262/#sec-instanceofoperator

```js
 class MyArr extends Array {
    constructor(...args) {
        super(...args);
    } 
}
const a = new MyArr(1,2);
a instanceof MyArr // should be true but false in jint
```

Not sure if this is unique to classes or a a more general problem

From spec:
>1. If Type(target) is not Object, throw a TypeError exception.
>2. Let instOfHandler be ? GetMethod(target, @@hasInstance).
>3. If instOfHandler is not undefined, then
>a. Return ! ToBoolean(? Call(instOfHandler, target, « V »)).
>4. If IsCallable(target) is false, throw a TypeError exception.
>5. Return ? OrdinaryHasInstance(target, V).

My understanding that jint does just the step 5 and step 3 doesn't work properly.

### PR DESCRIPTION
**Pull request by lahma**
Added tests cases, went trough logic and aligned with spec. The original test case didn't fail in dev either though...

fixes #874

### CODE REVIEW

File: Jint/Native/JsValue.cs [hunk 1]
```diff
@@ -566,6 +590,43 @@ internal virtual JsValue DoClone()
 
         internal virtual bool IsCallable => this is ICallable;
 
+        /// <summary>
+        /// https://tc39.es/ecma262/#sec-ordinaryhasinstance
```
Comment (sebastienros) [inline Jint/Native/JsValue.cs:594]: I was wondering such a weird name ... well it's the specs

**Review by sebastienros — APPROVED** [review]

File: Jint/Native/JsValue.cs (hunk 1 above)
Comment (lahma) [reply Jint/Native/JsValue.cs:594]: Indeed, I had trouble accepting it too 😄
