### PR TITLE
Fix block-scoped function registrations

### LINKED ISSUE #857: Problem with using functions when Strict option is enabled, since 3.0.26
Hi
The following test passes in version 3.0.25 (and older), but started failing since 3.0.26 
```c#
using Jint;
using Jint.Native;
using Xunit;

namespace Tryouts
{
    public class Program
    {
        public static void Main()
        {
            var script = @"
function execute(doc, args){
    var i = doc;
    {
        function doSomething() {
            return 'ayende';
        }

        i.Name = doSomething();
    }
}
";

            var engine = new Engine(options =>
            {
                options.Strict();
            });
            engine.Execute(script);

            var user = new User();
            var args = new []
            {
                JsValue.FromObject(engine, user)
            };

            var call = engine.GetValue("execute").TryCast<ICallable>();
            call.Call(Undefined.Instance, args); // throws JavaScriptException: 'doSomething is not defined', since version 3.0.26


            Assert.Equal("ayende", user.Name);

        }

        private class User
        {
            public string Name { get; set; }
        }
    }
}


```

Note that if we remove from the script the curly brackets that start after `var i = doc;` then the test passes. 
Same if `Strict` option is disabled.

### PR DESCRIPTION
**Pull request by lahma**
fixes #857

### CODE REVIEW

File: Jint/Runtime/Interpreter/JintStatementList.cs [hunk 1]
```diff
@@ -113,19 +113,19 @@ public Completion Execute()
...
-                var variableDeclaration = lexicalDeclarations[i];
+                var d = declarations[i];
                 boundNames.Clear();
-                variableDeclaration.GetBoundNames(boundNames);
+                d.GetBoundNames(boundNames);
                 for (var j = 0; j < boundNames.Count; j++)
                 {
                     var dn = boundNames[j];
-                    if (variableDeclaration.Kind == VariableDeclarationKind.Const)
+                    if (d is VariableDeclaration { Kind: VariableDeclarationKind.Const })
```
Comment (sebastienros) [inline Jint/Runtime/Interpreter/JintStatementList.cs:128]: you couldn't resist

Comment (lahma) [reply Jint/Runtime/Interpreter/JintStatementList.cs:128]: Rider/R# made me do it 😇
